---
apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: "flink-deployment-pv"
spec:
  capacity:
    storage: "50Gi"
  storageClassName: "local-storage"
  volumeMode: "Filesystem"
  accessModes:
  - "ReadWriteMany"
  persistentVolumeReclaimPolicy: "Delete"
  local:
    path: "/mnt/flink-job"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: "kubernetes.io/hostname"
          operator: "In"
          values:
          - "node1"
          - "node2"
          - "node3"
