---
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "flink-deployment-pvc"
  namespace: "flink"
spec:
  accessModes:
  - "ReadWriteMany"
  resources:
    requests:
      storage: "50Gi"
  storageClassName: "local-storage"
  volumeMode: "Filesystem"
  volumeName: "flink-deployment-pv"
status:
  accessModes:
  - "ReadWriteMany"
  capacity:
    storage: "50Gi"
