#!/bin/bash

HOST_PREFIX=$FPGA_CLIENT_HOST_PREFIX
CLIENT_STRING_ID=$STATEFULSET_ID
echo "Host: $HOST_PREFIX $CLIENT_STRING_ID"

export FPGA_CLIENT_HOST=${HOST_PREFIX}${CLIENT_STRING_ID}

START_INDEX=$ANTENNA_START_INDEX
CLIENT_INT_ID=$((CLIENT_STRING_ID))
INCREMENT=$ANTENNA_INDEX_INCREMENT
NEW_INDEX=$((START_INDEX * CLIENT_INT_ID * INCREMENT))
echo "Antenna start index: $NEW_INDEX"

export ANTENNA_START_INDEX=$NEW_INDEX

JAVA_OPS=${JAVA_OPS:--server -Xmx4096m -Xms1024m}
java $JAVA_OPS -jar /app/application.jar