#!/bin/bash

export CLIENT_STRING_ID=${HOSTNAME##*-}
HOST_PREFIX=$FPGA_CLIENT_HOST_PREFIX

export FPGA_CLIENT_HOST=${HOST_PREFIX}${CLIENT_STRING_ID}

START_INDEX=$ANTENNA_START_INDEX
CLIENT_INT_ID=$((CLIENT_STRING_ID))
INCREMENT=$ANTENNA_INDEX_INCREMENT
NEW_INDEX=$((START_INDEX * CLIENT_INT_ID * INCREMENT))

export ANTENNA_START_INDEX=$NEW_INDEX

JAVA_OPS=${JAVA_OPS:--server -Xmx4096m -Xms1024m}
java $JAVA_OPS -jar /app/application.jar